### ISSUE TITLE
bundle not installing the gem 'lita'; causes Gem::LoadError 

### ISSUE THREAD

**Issue by leowmjw** [litaio/lita#169]
Was trying to setup lita manually but hit the 'Gem::LoadError' error.  I had to install the 'lita' gem manually.  I would have thought the dependency 'lita' would been pulled in automatically by bundler.  Thoughts?

Observation
==========

**vagrant@precise64:/vagrant$ ruby --version**
```
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
```

**vagrant@precise64:/vagrant$ cat Gemfile**
```
source "https://rubygems.org"

gemspec

gem "lita-default-handlers"
gem "lita-alias"
gem 'lita-ai'
gem "lita-abuse"
gem "lita-telegram"
gem "lita-slack"
gem "lita-irc"
gem 'redis', '~>3.2'
```

**vagrant@precise64:/vagrant$ bundle**
```
...
Bundle complete! 16 Gemfile dependencies, 77 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
vagrant@precise64:/vagrant$ lita new
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'lita' (>= 0) among 85 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/vagrant/.gem/ruby/2.2.4:/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0', execute `gem env` for more information
	from /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /home/vagrant/.gem/ruby/2.2.4/bin/lita:22:in `<main>'
```

**vagrant@precise64:/vagrant$ gem install lita**
```
Fetching: lita-4.7.0.gem (100%)
Successfully installed lita-4.7.0
Parsing documentation for lita-4.7.0
Installing ri documentation for lita-4.7.0
Done installing documentation for lita after 1 seconds
1 gem installed
vagrant@precise64:/vagrant$ lita new
       exist  lita
   identical  lita/Gemfile
   identical  lita/lita_config.rb
```

**Comment by harlanbarnes** [comment]
To do what you want to do, you need to use `--binstubs` (I think).

```
bundle --binstubs /path/to/wherever/you/want/the/lita/bin
```

For example:

```
bundle --binstubs ~/bin
```

Then you can do:

```
~/bin/lita new
```

More details on bundle install [here](http://bundler.io/bundle_install.html)

**Comment by leowmjw** [comment]
Thanks @harlanbarnes; it works!
