### ISSUE TITLE
Lita not getting @here in slack

### ISSUE THREAD

**Issue by kendrickm** [litaio/lita#201]
I'm trying to write a plugin that listens for someone to use '@here' in a channel. It would then compare them against a specific group, and if they're not in that group give them a polite private message asking them not to notify everyone in the channel. The issue I'm having is it seems that @here isn't getting handled like normal text is. I created a test route that simply echoed any text back it heard, and it did fine until @here was used. I then see this stack trace

```
Slack API call to chat.postMessage returned an error: no_text.
Full backtrace:
/var/bundle/ruby/2.3.0/gems/lita-slack-1.8.0/lib/lita/adapters/slack/api.rb:99:in `call_api'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.8.0/lib/lita/adapters/slack/api.rb:59:in `send_messages'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.8.0/lib/lita/adapters/slack.rb:43:in `send_messages'
/var/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/robot.rb:129:in `send_messages'
/var/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/message.rb:93:in `reply'
```

Is this a slack issue(not sending that message through their bot api) or something on the lita side? I'm not finding much searching around for other people trying to do this.

Thanks

**Comment by kendrickm** [comment]
I just realized the slack integration is it's own repo, I'll close this question and re-open it over there.
