### ISSUE TITLE
undefined method run in version 4.7.1?

### ISSUE THREAD

**Issue by wesm-outreach** [litaio/lita#205]
```
$ bundle exec lita                                                                                                                                                                                            ‹ruby-2.3.3@minion›
/Users/wes/.rvm/gems/ruby-2.3.3@minion/gems/lita-4.7.1/lib/lita/cli.rb:77:in `start': undefined method `run' for Lita:Module (NoMethodError)
	from /Users/wes/.rvm/gems/ruby-2.3.3@minion/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/wes/.rvm/gems/ruby-2.3.3@minion/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/wes/.rvm/gems/ruby-2.3.3@minion/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/wes/.rvm/gems/ruby-2.3.3@minion/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/wes/.rvm/gems/ruby-2.3.3@minion/gems/lita-4.7.1/bin/lita:6:in `<top (required)>'
	from /Users/wes/.rvm/gems/ruby-2.3.3@minion/bin/lita:22:in `load'
	from /Users/wes/.rvm/gems/ruby-2.3.3@minion/bin/lita:22:in `<main>'
	from /Users/wes/.rvm/gems/ruby-2.3.3@minion/bin/ruby_executable_hooks:15:in `eval'
	from /Users/wes/.rvm/gems/ruby-2.3.3@minion/bin/ruby_executable_hooks:15:in `<main>'
```

Is this version of the gem broken?

here's my `lita_config.rb` file:
```
require 'bundler'
Lita.configure do |config|
  config.robot.name = "Lita"
  config.robot.mention_name = "lita"
  config.robot.log_level = :debug
  config.robot.adapter = :shell
  config.redis.host = "localhost"
end
```

**Comment by ghostsquad** [comment]
nvm, I did `bundle install`, instead of `gem install`. bundle 👎

**Comment by wesm-outreach** [comment]
nvm, I did `bundle install`, instead of `gem install`. bundle 👎
