### ISSUE TITLE
`lita new` failure on fresh installation; missing io-console gem

### ISSUE THREAD

**Issue by ncolton** [litaio/lita#56]
Fresh install on a new ec2 instance.
Prior to this I had run:
- sudo yum install openssl-devel.x86-64
- sudo gem2.0 install lita
  Then, to create a new _lita_ configuration:

```
~ $ lita new
/usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- io/console (LoadError)
    from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor/shell/basic.rb:2:in `<top (required)>'
    from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor/shell/color.rb:1:in `<top (required)>'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor/shell.rb:17:in `shell'
    from /usr/local/share/ruby/gems/2.0/gems/thor-0.19.1/lib/thor/base.rb:439:in `start'
    from /usr/local/share/ruby/gems/2.0/gems/lita-3.2.0/bin/lita:6:in `<top (required)>'
    from /usr/local/bin/lita:23:in `load'
    from /usr/local/bin/lita:23:in `<main>'
~ $
```

A bit of hunting suggested that I needed to install the _io-console_ gem. After installing that gem:

```
~ $ lita new
      create  lita
      create  lita/Gemfile
      create  lita/lita_config.rb
~ $
```

The list of gems installed after io-console was added:

```
activesupport (4.1.1)
bigdecimal (1.2.0)
bundler (1.6.2)
faraday (0.9.0)
ffi (1.9.3)
hashie (3.0.0)
http_router (0.11.1)
i18n (0.6.9)
ice_nine (0.11.0)
io-console (0.4.2)
json (1.7.7)
lita (3.2.0)
minitest (5.3.4)
multi_json (1.10.1)
multipart-post (2.0.0)
mumble-ruby (1.0.2)
opus-ruby (0.0.1)
psych (2.0.0)
puma (2.8.2)
rack (1.5.2)
rdoc (4.0.1)
redis (3.0.7)
redis-namespace (1.4.1)
ruby_protobuf (0.4.11)
thor (0.19.1)
thread_safe (0.3.4)
tzinfo (1.2.1)
url_mount (0.2.1)
```

**Comment by LeonLiADSK** [comment]
Thanks you ncolton , I resolved this after 
yum -y install libxslt-devel rubygem-io-console rubygem20-nokogiri
